version: "3"

services:
  domserver:
    container_name: domserver
    image: itsniklas/domjudge-domserver-nightly:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - domserver_public_images:/opt/domjudge/domserver/webapp/public/images
      - domserver_public_css:/opt/domjudge/domserver/webapp/css/custom
      - domserver_public_js:/opt/domjudge/domserver/webapp/public/js/custom
      - domserver_public_docs:/opt/domjudge/domserver/webapp/public/docs
    ports:
      - 12345:80
    depends_on:
      - mariadb
    env_file:
      - domserver.env
    links:
      - mariadb:mariadb
    restart: on-failure:3

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 13306:3306
    env_file:
      - domserver.env
    command: --max-connections=1000 --innodb-log-file-size=2G --max-allowed-packet=1G

  phpmyadmin:
    container_name: myadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    depends_on:
      - mariadb
    env_file:
      - domserver.env
    links:
      - mariadb:mariadb

volumes:
  mariadb:
  domserver_public_images:
  domserver_public_css:
  domserver_public_js:
  domserver_public_docs:
