name: Build and Publish DOMjudge

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 3 AM
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check-commit.outcome }}

    steps:
    - name: Checkout DOMjudge Repository
      uses: actions/checkout@v3
      with:
        repository: 'domjudge/domjudge'
        ref: 'main'

    - name: Get Latest Commit Hash
      run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Try Pulling the Image with Specific Tag and Set Output
      id: check-commit
      continue-on-error: true
      run: |
        docker pull itsniklas/domjudge-domserver-nightly:8.3.0DEV-${{ env.COMMIT_HASH }}

  build:
    needs: check
    if: needs.check.outputs.status == 'failure'
    runs-on: ubuntu-latest

    steps:
    # Rest of the steps for building and publishing
    - name: Checkout DOMjudge Repository
      uses: actions/checkout@v2
      with:
        repository: 'domjudge/domjudge'
        ref: 'main'
        path: 'domjudge'

    - name: Get Latest Commit Hash
      run: cd domjudge && echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

    - name: Checkout DOMjudge Docker Repository
      uses: actions/checkout@v2
      with:
        path: 'domjudge-docker'

    # - name: Download DOMjudge Snapshot
    #   run: wget https://www.domjudge.org/snapshot/domjudge-snapshot-$(date +%Y%m%d).tar.gz -O domjudge-docker/domjudge-packaging/docker/domjudge.tar.gz
    
    - name: Create DOMjudge Snapshot
      run: tar -czf domjudge-docker/domjudge-packaging/docker/domjudge.tar.gz domjudge
    
    - name: Build DOMjudge
      run: |
        cd domjudge-docker/domjudge-packaging/docker/
        ./build-domjudge.sh itsniklas/domjudge-domserver-nightly:8.3.0DEV-${{ env.COMMIT_HASH }}
        docker tag itsniklas/domjudge-domserver-nightly:8.3.0DEV-${{ env.COMMIT_HASH }} itsniklas/domjudge-domserver-nightly:latest

    - name: Build Judgehost
      run: |
        cd domjudge-docker/domjudge-packaging/docker/
        ./build-judgehost.sh itsniklas/domjudge-judgehost-nightly:8.3.0DEV-${{ env.COMMIT_HASH }}
        docker tag itsniklas/domjudge-judgehost-nightly:8.3.0DEV-${{ env.COMMIT_HASH }} itsniklas/domjudge-judgehost-nightly:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish DOMjudge Image
      run: |
        docker push itsniklas/domjudge-domserver-nightly:8.3.0DEV-${{ env.COMMIT_HASH }}
        docker push itsniklas/domjudge-domserver-nightly:latest

    - name: Publish Judgehost Image
      run: |
        docker push itsniklas/domjudge-judgehost-nightly:8.3.0DEV-${{ env.COMMIT_HASH }}
        docker push itsniklas/domjudge-judgehost-nightly:latest
